### ISSUE TITLE
Dedicated tracker objects for :removing, :changed and :added

### ISSUE THREAD

**Issue by Aloroid** [centau/ecr#13]
Traditional systems that run every frame are commonly used among ECS patterns. You query for certain components, loop through them, modify and then go to the next system. Currently, this is all handled using `:track`, but it is inadequate for certain situations. Writing replication code is as result way harder to fit in a traditional system, as it is hard to detect when a object is added, removed or changed.

Currently, I have a `use_event` function that will cache and store the results from a `Signal`-like object and use that to track explicitly for `:added`, `:removing` and `:changed`. All is fine until `:removing` comes into play. Because `:removing` doesn't return the values of the components you track, it is even harder to write code that needs to detect when a entity is removed inside traditional systems, as we'll run into a issue where we need certain data, but that data just doesn't exist anymore because it already has been removed.

Having dedicated tracker objects that can track explicitly for when a component is added, removed or changed can solve this issue and removes the need for a `use_event` function just for ECR.

**Comment by centau** [comment]
I have plans to expand on the observer API which would make them more flexible, something that would allow you to decide if you want to track only added, changed or removed components, or a combination of them which should solve your problem.

I do also want to note that although `Registry:removing()` does not directly give you the current component value, you can still retrieve the value for that component within the listener using `Registry:get()` as the event fires *before* the component is removed which should also solve your issue for now.

**Comment by Aloroid** [comment]
Correct, `registry:removing()` fires before the component is removed, but in traditional systems, where I have to use the `use_event` function this falls apart, as by the time this system runs, it's already completely removed and can no longer process any old components.

**Comment by centau** [comment]
In this case if you're using the events to cache entities for later processing by a system, you'd just also store the old value alongside the entity so they can be processed together. This is basically what an observer implements already.

**Comment by centau** [comment]
I'm going to close this issue because I don't think the use is strong enough to have built-in dedicated tracker objects for each event. There are many slight variations to how users would want this, whether they want to track only the entities, or entities and their component values, only track the latest, or track the entire history of changes, etc. An API to accommodate all of this would be cumbersome.

The events already allow users to create their own tracker objects that do exactly as they need.
