### ISSUE TITLE
world:track returns unchanged components

### ISSUE THREAD

**Issue by piquu** [centau/ecr#20]
```lua
local ReplicatedStorage = game:GetService('ReplicatedStorage')
local RunService = game:GetService('RunService')

local ecr = require(ReplicatedStorage.Lib.ecr)

local Health = ecr.component() :: number

local function healht(world: ecr.Registry)
	for id, health in world:track(Health) do
		print(id, health)
	end
end

local world = ecr.registry

local id = world:create()
world:set(id, Health, 100)

RunService.Stepped:Connect(function()
	healht(world)
end)
```
https://github.com/centau/ecr/assets/76695865/697fdc85-db68-4bf7-83fa-6dd8efb6e02a

im not making any changes to the entity but world:track still returns it for some reason

**Comment by centau** [comment]
`Registry:track()` returns an `Observer` which treats all existing entities are "changed" for the first time when you iterate it.

What you are actually doing there is creating a new observer every time your `healht` function runs.

What you likely want to do instead is to only call `Registry:track()` once outside of the function, store the observer aside, and iterate that same observer each time `healht` runs.
